# Site settings
title: Your Website Title
description: A brief description of your website
theme: jekyll-theme-cayman

# URL settings
baseurl: "" # Leave this empty for GitHub Pages

# Build settings
markdown: kramdown
